/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import BE.Fireman;
import BE.ErrorReport;
import BE.TeamLeaderReport;
import BLL.EmployeeBLL;
import BLL.ErrorReportBLL;
import BLL.TLReportBLL;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Nicolai
 */
public class MainFrame extends javax.swing.JFrame {
        
    EmployeeBLL EBLL;
    ErrorReportBLL ERBLL;
    TLReportBLL TLRBLL;
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Brand Og Redning");
        setLocationRelativeTo(null);
        setResizable(true);
        
        setButtons();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtCpr = new javax.swing.JTextField();
        ComboboxBil = new javax.swing.JComboBox();
        txtTidsrum = new javax.swing.JTextField();
        txtKørt = new javax.swing.JTextField();
        BtnGem = new javax.swing.JButton();
        BtnReperation = new javax.swing.JButton();
        BtnHoldLeder = new javax.swing.JButton();
        txtHvad = new javax.swing.JTextField();
        txtIndsats = new javax.swing.JTextField();
        CheckBoxCH = new javax.swing.JCheckBox();
        CheckBoxX = new javax.swing.JCheckBox();
        CheckBoxSt = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        RBtnIndsats = new javax.swing.JRadioButton();
        RBtnØvelse = new javax.swing.JRadioButton();
        RBtnBandvagt = new javax.swing.JRadioButton();
        RBtnStandby = new javax.swing.JRadioButton();
        RBtnFalck = new javax.swing.JRadioButton();
        RBtnFølgeskade = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        RBtnSkade = new javax.swing.JRadioButton();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCpr.setText("Navn CPR?");

        ComboboxBil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bil" }));

        txtTidsrum.setText("Tidsrum");

        txtKørt.setText("Kørt Timer");

        BtnGem.setText("Gem");

        BtnReperation.setText("Reperation...");

        BtnHoldLeder.setText("Hold Leder...");

        txtIndsats.setText("Navn på indsats");

        CheckBoxCH.setText("CH");

        CheckBoxX.setText("X");

        CheckBoxSt.setText("ST");

        jLabel1.setText("Fremmøde Ved");

        RBtnIndsats.setText("Indsats");

        RBtnØvelse.setText("Øvelse");

        RBtnBandvagt.setText("Bandvagt");

        RBtnStandby.setText("Stand-by");

        RBtnFalck.setText("Arbejde Falck");

        RBtnFølgeskade.setText("Følgeskade");

        jLabel2.setText("Hvad");

        RBtnSkade.setText("Andet (hvad)");

        jTextField6.setText("/ /");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnReperation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnHoldLeder))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCpr)
                            .addComponent(ComboboxBil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTidsrum)
                            .addComponent(txtKørt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxSt)
                            .addComponent(CheckBoxCH)
                            .addComponent(txtIndsats, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(CheckBoxX)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHvad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RBtnIndsats)
                                    .addComponent(RBtnØvelse)
                                    .addComponent(RBtnBandvagt)
                                    .addComponent(RBtnStandby)
                                    .addComponent(RBtnFalck)
                                    .addComponent(RBtnFølgeskade)
                                    .addComponent(RBtnSkade))
                                .addGap(15, 15, 15))
                            .addComponent(jLabel2))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RBtnIndsats)
                        .addGap(4, 4, 4)
                        .addComponent(RBtnØvelse)
                        .addGap(7, 7, 7)
                        .addComponent(RBtnBandvagt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBtnStandby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBtnFalck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBtnFølgeskade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBtnSkade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHvad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboboxBil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTidsrum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKørt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(CheckBoxCH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckBoxX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckBoxSt)))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIndsats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGem)
                    .addComponent(BtnReperation)
                    .addComponent(BtnHoldLeder))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGem;
    private javax.swing.JButton BtnHoldLeder;
    private javax.swing.JButton BtnReperation;
    private javax.swing.JCheckBox CheckBoxCH;
    private javax.swing.JCheckBox CheckBoxSt;
    private javax.swing.JCheckBox CheckBoxX;
    private javax.swing.JComboBox ComboboxBil;
    private javax.swing.JRadioButton RBtnBandvagt;
    private javax.swing.JRadioButton RBtnFalck;
    private javax.swing.JRadioButton RBtnFølgeskade;
    private javax.swing.JRadioButton RBtnIndsats;
    private javax.swing.JRadioButton RBtnSkade;
    private javax.swing.JRadioButton RBtnStandby;
    private javax.swing.JRadioButton RBtnØvelse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtCpr;
    private javax.swing.JTextField txtHvad;
    private javax.swing.JTextField txtIndsats;
    private javax.swing.JTextField txtKørt;
    private javax.swing.JTextField txtTidsrum;
    // End of variables declaration//GEN-END:variables

    public void setButtons(){
        
    
        BtnReperation.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae){
                new ReperationsFrame().setVisible(true);    
            }
        });
    
        BtnHoldLeder.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae){
                new HoldLederFrame().setVisible(true);    
            }
        });
    
        BtnGem.addActionListener(new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent ae){
                Fireman f = new Fireman(txtCpr.getText(), txtHvad.getText(), txtIndsats.getText(), txtKørt.getText(), txtTidsrum.getText(), ComboboxBil.getSelectedItem().toString(),buttonGroup1.getSelection().toString());
            }
        });

   }
    
    class myKeyListener extends KeyAdapter{ 
        
        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyChar() == KeyEvent.VK_ENTER) {
            }  
                
            }
    }
}